spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8080/
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true