spring:
  application:
    name: property
  profiles:
    active:
    - prod
  config:
    import: optional:configserver:http://localhost:8080/

management:
  endpoints:
    web:
      exposure:
        include: "*"
          
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true