spring:
  application:
    name: configserver
  profiles:
    active: prod
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhitechdecrypt/spring-b-microservice-zipkin-prometheus-grafana-config.git
          clone-on-start: true
          timeout: 5
          default-label: main
          force-pull: true
          
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

          